function [TimeseriesDataTable, nData] = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  TIMESERIESDATATABLE = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TIMESERIESDATATABLE = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  TimeseriesDataTable = importfile1("C:\Users\Mareim\OneDrive - Coventry University\Data\Data on CNC temp\data\2017-02-28.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-May-2019 18:01:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 56);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "X", "Y", "Z", "DCH0101", "DCH0102", "DCH0103", "DCH0104", "DCH0105", "DCH0106", "DCH0107", "DCH0108", "DCH0201", "DCH0202", "DCH0203", "DCH0204", "DCH0205", "DCH0206", "DCH0207", "DCH0208", "DCH0301", "DCH0302", "DCH0303", "DCH0304", "DCH0305", "DCH0306", "DCH0307", "DCH0308", "DCH0401", "DCH0402", "DCH0403", "DCH0404", "DCH0405", "DCH0406", "DCH0407", "DCH0408", "DCH0501", "DCH0502", "DCH0503", "DCH0504", "DCH0505", "DCH0506", "DCH0507", "DCH0508", "DCH0601", "DCH0602", "DCH0603", "DCH0604", "DCH0605", "DCH0606", "DCH0607", "DCH0608", "DCH0701", "DCH0702", "DCH0703", "DCH0704"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "InputFormat", "HH:mm:ss");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TimeseriesDataTable = readtable(filename, opts);
nData = normalize(TimeseriesDataTable(:,2:end),'range',[0,1]);
end