% run this script to load models as initially written in the first code
% draft
layers1 = [... 
    sequenceInputLayer(numFeatures,'Name','InputLayer1'),...
    lstmLayer(numHiddenUnits*3,'OutputMode','sequence','Name','LSTM_Layer'),...
    fullyConnectedLayer(300,'Name','FC_Layer1'),...
    lstmLayer(300,'Name','LSTM_Layer2','OutputMode','sequence'),...
    fullyConnectedLayer(60,'Name','FC_Layer2'),...
    lstmLayer(60,'Name','LSTM_Layer3','OutputMode','sequence'),...
    fullyConnectedLayer(numResponses,'Name','FC_Layer3'),...
    regressionLayer('Name','RegressionLayer'),...
    ];

layersGlorot = [... 
    sequenceInputLayer(numFeatures,'Name','InputLayer1'),...
    lstmLayer(numHiddenUnits*widthFactor,'OutputMode','sequence','InputWeightsInitializer','Glorot','Name','LSTM_Layer1'),...
    fullyConnectedLayer(numHiddenUnits*widthFactor/2,'Name','FC_Layer1'),...
    lstmLayer(numHiddenUnits*widthFactor/2,'OutputMode','sequence','InputWeightsInitializer','Glorot','Name','LSTM_Layer2'),... 
    fullyConnectedLayer(numHiddenUnits*widthFactor/4,'Name','FC_Layer2'),...
    lstmLayer(numHiddenUnits*widthFactor/4,'OutputMode','sequence','InputWeightsInitializer','Glorot','Name','LSTM_Layer3'),... 
    fullyConnectedLayer(numHiddenUnits,'Name','FC_Layer3'),...
    lstmLayer(numHiddenUnits/2,'OutputMode','sequence','InputWeightsInitializer','Glorot','Name','LSTM_Layer4'),... 
    fullyConnectedLayer(numResponses,'name','FC_Layer_FINAL'),...
    regressionLayer('Name','RegressionLayer'),...
    ];
   
layersHe = [... 
    sequenceInputLayer(numFeatures,'Name','InputLayer1'),...
    lstmLayer(numHiddenUnits*widthFactor,'OutputMode','sequence','InputWeightsInitializer','He','Name','LSTM_Layer1'),...
    fullyConnectedLayer(numHiddenUnits*widthFactor/2,'Name','FC_Layer1'),...
    lstmLayer(numHiddenUnits*widthFactor/2,'OutputMode','sequence','InputWeightsInitializer','He','Name','LSTM_Layer2'),... 
    fullyConnectedLayer(numHiddenUnits*widthFactor/4,'Name','FC_Layer2'),...
    lstmLayer(numHiddenUnits*widthFactor/4,'OutputMode','sequence','InputWeightsInitializer','He','Name','LSTM_Layer3'),... 
    fullyConnectedLayer(numHiddenUnits,'Name','FC_Layer3'),...
    lstmLayer(numHiddenUnits/2,'OutputMode','sequence','InputWeightsInitializer','He','Name','LSTM_Layer4'),... 
    fullyConnectedLayer(numResponses,'name','FC_Layer_FINAL'),...    
    regressionLayer('Name','RegressionLayer'),...
    ];
   
layersNN = [... 
    sequenceInputLayer(numFeatures,'Name','InputLayer1'),...
    lstmLayer(numHiddenUnits*widthFactor,'OutputMode','sequence','InputWeightsInitializer','narrow-normal','Name','LSTM_Layer1'),...
    fullyConnectedLayer(numHiddenUnits*widthFactor/2,'Name','FC_Layer1'),...
    lstmLayer(numHiddenUnits*widthFactor/2,'OutputMode','sequence','InputWeightsInitializer','narrow-normal','Name','LSTM_Layer2'),... 
    fullyConnectedLayer(numHiddenUnits*widthFactor/4,'Name','FC_Layer2'),...
    lstmLayer(numHiddenUnits*widthFactor/4,'OutputMode','sequence','InputWeightsInitializer','narrow-normal','Name','LSTM_Layer3'),... 
    fullyConnectedLayer(numHiddenUnits,'Name','FC_Layer3'),...
    lstmLayer(numHiddenUnits/2,'OutputMode','sequence','InputWeightsInitializer','narrow-normal','Name','LSTM_Layer4'),...
    fullyConnectedLayer(numResponses,'Name','FC_Layer_FINAL'),...
    regressionLayer('Name','RegressionLayer'),...
    ];