% create figure from data
xvector1 = [0, 0.05, 0.10, 0.15];
yvector1 = [6.35, 5.36, 4.72, 4.34];

createfigure(xvector1, yvector1)

function createfigure(xvector1, yvector1)
%CREATEFIGURE(xvector1, yvector1)
%
%

%  Auto-generated by MATLAB on 24-Jan-2019 21:39:26

% Create figure
figure1 = figure('WindowState','maximized');
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.134895833333333 0.11 0.770104166666663 0.815]);
hold(axes1,'on');

% Create bar
bar(xvector1,yvector1,...
    'FaceColor',[0.650980392156863 0.650980392156863 0.650980392156863]);

% Create ylabel
ylabel({'Maximum Compressive Strength (MPa)'},...
    'HorizontalAlignment','center');

% Create xlabel
xlabel({'Percentage of additional PCM mass (%)'},...
    'HorizontalAlignment','center');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.03 0.18]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XTick',[-0.05 0 0.05 0.1 0.15 0.2],'XTickLabel',...
    {'','0','5','10','15',''});
end
