function createline(figure1)
%CREATELINE(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 16-Aug-2018 14:53:20

% Create line
annotation(figure1,'line',[0.129166666666667 0.563020833333333],...
    [0.110111111111111 0.585470085470085]);

