function createtextbox(figure1)
%CREATETEXTBOX(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 19-Aug-2018 17:06:55

% Create textbox
annotation(figure1,'textbox',[0.93 0.81 0.04 0.1],...
    'String','V_C = 150.72 m/min',...
    'FitBoxToText','off');

