%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\mareim\Desktop\M101CCEM\plotdata.xlsx
%    Worksheet: getData (1)
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/10/08 15:05:05

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\mareim\Desktop\M101CCEM\plotdata.xlsx','getData (1)','A3:E1204','',@convertSpreadsheetExcelDates);
stringVectors = string(raw(:,[2,3]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,5]);
dates = dates(:,4);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
plotdata = table;

%% Allocate imported array to column variable names
plotdata.nodeid = data(:,1);
plotdata.house = categorical(stringVectors(:,1));
plotdata.room = categorical(stringVectors(:,2));
plotdata.time = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
plotdata.value = data(:,2);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% plotdata.time=datenum(plotdata.time);

%% Clear temporary variables
clearvars data raw dates stringVectors;

%% Plot the data
tt = table2timetable(plotdata);
nc = categories(plotdata.room(:));
rooms = nominal(plotdata.room);
legendEntries = getlevels(rooms);
roomColor = 0;
nc = countcats(plotdata.room);
numcats = nc;
%% Plot
figure(1); clf reset;
set(gca, 'ColorOrder',jet(13));
for n = 1:13
  plot(tt.time(tt.room == rooms{n}),tt.value(tt.room == rooms{n}))
  hold on
end
legend(rooms)
xlabel('Time')
ylabel('Temperature, /deg C')