function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------

% Crop the image using the predefined rectangle ---------------------------------
rect = [400 380 720 540];
[~, threshold] = edge(im,'sobel');
fudgeFactor = 0.5;
BWs = edge(im, 'sobel', threshold*fudgeFactor);
shapeMatrix = ...
    [0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 1 1 1 0 0 0 0 0 0 0;
     0 0 0 1 1 1 0 0 0 0 0 0;
     0 0 0 0 1 1 1 0 0 0 0 0;
     0 0 0 0 0 1 1 1 0 0 0 0;
     0 0 0 0 0 0 1 1 1 0 0 0;
     0 0 0 0 0 0 0 1 1 1 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0 0 0 0;];
SE = strel('arbitrary',shapeMatrix);
BWsdil = imdilate(BWs, SE);

imc = imcrop(im,rect);
%sprintf('Image of size %d by %d \n',imc.size(1),imc.size(2))
results.imcropped = imc;

%--------------------------------------------------------------------------
